### PR TITLE
❄️ Drop support for HHVM, add support for 7.2 -> Nightly

### LINKED ISSUE #16: Drop Support for PHP 5.5

### PR DESCRIPTION
**Pull request by svpernova09**
Closes #16

### CODE REVIEW

**Review by matthewtrask — APPROVED** [review]

**Comment by matthewtrask** [comment]
@svpernova09 are these CI failures expected?

**Comment by svpernova09** [comment]
I'll update the PR to allow `nightly` to fail since that's 7.3 currently. Looks like we need to investigate what's not happy with 7.2. Maybe a deprecated method.

**Comment by elazar** [comment]
Looks like incompatibilities with the older version of PHPUnit and its dependencies that are being used. I'd start there.

**Comment by svpernova09** [comment]
There we go. Just needed a composer update.

**Pull request merged**
