### PR TITLE
New improved ghosting algorithm, plus various other changes

### PR DESCRIPTION
**Pull request by Renegade334**
* Ghosting: if configured to do so, and if the primary nick is already in use on connection, the plugin will send a NickServ ghost command and then reclaim the nick
* Added the ability to specify custom regexes
* Added the ability to specify custom NickServ nick
* `nickserv.identified` event passes connection and event queue parameters to event callback (ref: #6)
* Removed the quit listener from Phergie2, which was broken anyway and not functionally compatible with the ghost feature; a fixed version of this functionality should be rewritten into a new NickRegain plugin

TODO:
* Calling `Connection::setNick()` when a nick change is received corresponding to the bot is something that should ideally be processed by the client, not this plugin

### CODE REVIEW

**Comment by elazar** [comment]
Any particular reason for requiring `phergie/phergie-irc-parser:~1.6`?

Re: the TODO, I agree that this makes sense. Please file an issue and/or PR against [the client repo](https://github.com/phergie/phergie-irc-client-react).

**Comment by Renegade334** [comment]
Selection of numeric parameter by index... there's no way of resolving that specific dependency through phergie-irc-bot-react.

**Comment by elazar** [comment]
The only reason that's working is [this `minimum-stability:dev` line](https://github.com/phergie/phergie-irc-plugin-react-nickserv/blob/f7788a6c5e05f8f3326727905dbf335bba4f8b69/composer.json#L12), which should really be taken out at this point. Here's what I propose:

1. You confirm that phergie/phergie-irc-parser#25 is ready for merging.
2. I merge it and tag a new parser release.
3. You modify this PR that it:
     1. removes `minimum-stability:dev`
     2. requires the newly tagged parser version
     3. requires`phpunit/phpunit:~4.6` and `phake/phake:~2` (we're currently using `phake/phake:2.0.0-beta2`, which I think may have been part of the reason `minimum-stability:dev` was there to begin with: we needed a particular bug fix from that version).
4. I'll merge this PR.

Thoughts?

**Comment by Renegade334** [comment]
I agree with removing `minimum-stability:dev`, and will make those recommended changes, but the change the dependency exists for is actually phergie/phergie-irc-parser#16 (which is part of tag 1.6), not phergie/phergie-irc-parser#25.

**Comment by sitedyno** [comment]
https://github.com/Renegade334/phergie-irc-plugin-react-nickserv/blob/devel/src/Plugin.php#L132

There doesn't seem to be a handleQuit method?

**Comment by Renegade334** [comment]
Good catch.

**Pull request merged**
